### ISSUE TITLE
SickRageInstaller.exe v0.5.3 blocked by Bitdefender advanced threat defence

### ISSUE THREAD

**Issue by tinel-c** [SickChill/windows-sickchill#15]
Tried to install it on D:\ and on C:\. Windows 10.
Previous version ends by stating there is a new installer available.
Install it manually and it works. Maybe it failed because I had git already installed?

At the end the installed finishes by bringing only Python.
This is due to the blockage of Bitdefender advance threat defense. After disabling it it installs it correctly.
Searching for a way to white list this by default.

**Comment by miigotu** [comment]
Its something to do with ssl iirc, i have no clue how to get around it. It is a false positive though, picling up on compressed scripts in PortableGit

**Comment by noderat** [comment]
Virus total results [here](https://www.virustotal.com/en/file/85b45b042e29b93a684f485b12a1f1a99577294c690117b661446f76163a11dc/analysis/1540887658/)
