### ISSUE TITLE
Sickrage is already installed error on reinstall

### ISSUE THREAD

**Issue by ConstantConfusion** [SickChill/windows-sickchill#24]
I attempted to install sickrage using the newest windows installer. Well.... windows 10 was doing this weird folder block thing that stopped the install... so I manually delete the sickrage folder.... then turned the windows security nonsense off.  
  
Now, whenever i try to reinstall it.... I keep getting this message.  
![image](https://user-images.githubusercontent.com/40719658/42126419-101446d6-7c4e-11e8-9f56-0f2003e571e9.png)
  
  
So, I go into windows to try to uninstall sickrage... and I get this message  
  
![image](https://user-images.githubusercontent.com/40719658/42126424-26b8aba2-7c4e-11e8-94a4-234cd23b8fae.png)
  
  
What other files should I remove to stop this reinstall message?

**Comment by Nocturnophile** [comment]
you need to delete the sickchill/sickrage service, open command prompt and type 'sc delete sickrage' or 'sc delete sickchill', whichever service you have.

**Comment by krelbourne** [comment]
Hi Nocturnophile.
I've tried the commands you suggest, but still get the error that SickChill is already installed.
Any ideas?!

**Comment by BeDazzler1** [comment]
You will need to delete the installer reference in the registry. Not sure if your GUID would be the same but the path should be: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\
Search for Sickchill and remove the key there. After that my installer worked again.
