### ISSUE TITLE
Randomly Quit

### ISSUE THREAD

**Issue by Matthewserta** [SickChill/windows-sickchill#26]
My SickChill randomly quit today, and i cant get it to relaunch. Its setup as a service so i cannot see any console output on it, And i have no idea where to look for any logs..
Running on windows 10 pro. No idea why it stopped working, it just randomly stopped and will not relaunch..
Not sure how to back everything up without it running so i can try a reinstall..

**Comment by Matthewserta** [comment]
Update, I did find C:\SickChill\Data\Logs 
After trying to start the service manually nothing populates... as if its not running at all.

**Comment by Jeka111111** [comment]
the same issue.  this is what worked, somewhat, for me.  
i uninstalled SickChill and chose to keep the data.  then renamed c:\sickchill.  then reinstalled SickChill with all the default settings.  then copied data folder to the new install (c:\sickchill\data).  then opened command as admin and ran
  C:\SickChill\Python\python.exe "C:\SickChill\SickChill\SickBeard.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"

it's working, meaning it's searching the "sites" for the files and sets uTorrent to download them.  it also parses properly through downloaded files and renames them.  but i get git_path error.  i already tried to add c:\sickchill\git\bin\ to git_path inside c:\sickchill\data\config.ini, but it did not help.  i will continue messing with it.

**Comment by Matthewserta** [comment]
Tried your above guide, At least im able to get an error now:

DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2j  26 Sep 2016) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "C:\SickChill\SickChill\SickBeard.py", line 70, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "C:\SickChill\SickChill\sickchill\views\__init__.py", line 23, in <module>
    from .authentication import LoginHandler, LogoutHandler
  File "C:\SickChill\SickChill\sickchill\views\authentication.py", line 35, in <module>
    from .index import BaseHandler
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 34, in <module>
    from jwt.algorithms import RSAAlgorithm as jwt_algorithms_RSAAlgorithm
ImportError: cannot import name RSAAlgorithm

So this is a nationwide outage and not just my problem? Makes me feel better about it being fixed then lol.
