### ISSUE TITLE
0.5.7 Installer says it's an old version

### ISSUE THREAD

**Issue by HaboMaster** [SickChill/windows-sickchill#28]
<img width="464" alt="Screenshot 2020-09-17 at 21 21 50" src="https://user-images.githubusercontent.com/25375598/93517992-7f6dc900-f92c-11ea-9f50-86a1753fa879.png">

This seems to be the latest version but complains that it is old.

**Comment by miigotu** [comment]
It literally is. there is a 0.5.8

**Comment by miigotu** [comment]
https://github.com/SickChill/windows-sickchill/releases/tag/v0.5.8
