### ISSUE TITLE
Error installing on Windows 10

### ISSUE THREAD

**Issue by brucegames10** [SickChill/windows-sickchill#31]
I'm trying to reinstall SickChill on my new PC. I downloaded SickChillInstaller.exe v0.5.9 and I get this error when it's trying to install PortableGit:
Runtime Error (at 126:640):

I'm running Windows 10 20H2 and I've tried installing in the old folder, a new folder,and running the installer as admin, but always the same error.

**Comment by AMSoftwareNL** [comment]
Same problem here on Windows Server 2019. 

Tried installing every possible VC++ redistributable, but did not help

**Comment by miigotu** [comment]
I'll spin up a windows vm as soon as I can, I have to be somewhere tonight though

**Comment by miigotu** [comment]
I did not test windows server yet, but I did test with a brand new fresh virtual machine from the freely available microsoft edge virtual machine images of windows 10. I did not have to install any updates or packages. I simply downloaded the installer, allowed it past defender or whatever it's called now, and installed it with next-next-next. Installed and started right up.

**Comment by brucegames10** [comment]
I got the error on a new Dell PC. I got SickChill running by downloading the source and installing Python and Git separately, but couldn't figure out why the installer was failing. Is there any more info I can provide to help?

**Comment by miigotu** [comment]
Check your antivirus logs

**Comment by miigotu** [comment]
Also installs on Windows server preview 2022 out of the box:
![image](https://user-images.githubusercontent.com/390379/114289738-2ee4c700-9a48-11eb-9bdf-fc09f5cfbd8c.png)

**Comment by brucegames10** [comment]
I'm using Windows built-in virus protection and there was nothing in the log. I tried turning off Real-time protection, but still Runtime Error (at 126:640). 

I tried downloading and installing PortableGit-2.12.2-64-bit.7z.exe and it installed without errors. I assumed the error was coming from the PortableGit install since it's the last thing I see on the screen, but maybe it's a later step. Could it be an error from the installer code?

I've seen this problem reported a few times in the past but nobody seemed to figure out what was going on. I'm happy to help try to figure this out.

**Comment by miigotu** [comment]
Are you using an administrator account?

**Comment by brucegames10** [comment]
Yes, I'm using an administrator account. I even tried running it as Admin. Always the same error.

**Comment by miigotu** [comment]
Up to date with windows update?

**Comment by miigotu** [comment]
Literally just throwing ideas out here because none of this makes sense. I've tested it many times and there are literally tens of thousands of people using this installer on windows with no issues. Only a handful of people with the issue.

**Comment by brucegames10** [comment]
I understand it's hard to fix when you can't see it fail. My system is updated, Windows 10 Version 20H2. I wonder it this could be it? My old computer was running Windows 10 Pro and this one has Windows 10 Home Single Language.

**Comment by brucegames10** [comment]
I appreciate the ideas. Can the installer generate a log file?

**Comment by miigotu** [comment]
Im going to rewrite parts of the installer, but you should check your temp folder for seed.ini, installer.ini, python-*.zip, PortableGit*.exe. Im pretty sure a failed download is in your temp folder.

**Comment by brucegames10** [comment]
3 subdirectories get created. One has idp.dll, installer.ini, python-*.zip, PortableGit*.exe, and _setup64.tmp (in a subdir), but they get deleted when I click OK on the error dialog. Looks like installer.ini has the contents I see if I download seed.ini. The other 2 directories have identical copies of SickChillInstaller.tmp.

**Comment by miigotu** [comment]
Delete them all

**Comment by brucegames10** [comment]
They were only there while the installer was still running. As soon as I clicked OK on the error dialog, they all got deleted.

**Comment by miigotu** [comment]
Meh I'm gonna try and rewrite the installer using the newer innosetup

**Comment by nortuzar** [comment]
Today I updated my sickchill installation, after that it wont load. I erase everything and was going to post regarding theRuntime Error (at 126:640): but then I saw the release 0.5.11 that fixed the installation process. 
The process went fine but now it wont load the web service, Unable to connect

**Comment by F3TTT** [comment]
> 
> 
> Today I updated my sickchill installation, after that it wont load. I erase everything and was going to post regarding theRuntime Error (at 126:640): but then I saw the release 0.5.11 that fixed the installation process.
> The process went fine but now it wont load the web service, Unable to connect

same here.  service shows as paused still.  thanks for jumping on this so fast though!

**Comment by miigotu** [comment]
For windows, reinstall with the new installer: https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.0
