### ISSUE TITLE
New Installer not creating a working sickchill service 

### ISSUE THREAD

**Issue by knockreff** [SickChill/windows-sickchill#32]
Trying to reinstall sickchill after an update failure.  

using the 6.0 release on windows 10 version 20H2

Initially watching the installer  it was throwing python path warnings.   after adding the directory to path there is no longer warnings that I can see as it installs,  but after  completing there is only the data, installer and python3 folders in the install directory (no sickchill).

**Comment by miigotu** [comment]
There isn't supposed to be a SickChill folder anymore. It is in the `c:/SickChill/python3/tools/lib/python3.8/site-packages/sickchill` folder. 

The script to run it is in
`c:/SickChill/python3/tools/scripts/sickchill.py`

Just start the service after using the new installer.

**Comment by knockreff** [comment]
Thanks for the additional info.  the issue appears to be how it is being installed and launched as a service as I can launch sickchill from a admin command prompt using the same arguments as NSSM' however when launching as a service or using nssm from a command prompt it is erroring out.  
[error.txt](https://github.com/SickChill/windows-sickchill/files/6803823/error.txt)

**Comment by miigotu** [comment]
Looks like you interrupted the install, the first launch can take a few minutes before the GUI is available, and there are no logs generated while it is populating the virtual environment. Uninstall, delete c:\sickchill\python3, reinstall, and do not stop the service. Let it finish until the web GUI comes up.

**Comment by knockreff** [comment]
I did a uninstall and reinstall with the same end result.

watching the service from taskman shows that the service is erroring out (pausing) when initially installing.

**Comment by miigotu** [comment]
> I did a uninstall and reinstall with the same end result.
> 
> watching the service from taskman shows that the service is erroring out (pausing) when initially installing.  
> 
> 

You need to use the new installer
https://github.com/SickChill/windows-sickchill/releases/download/v0.6.0/SickChillInstaller.exe

**Comment by knockreff** [comment]
This is with the current 0.6.0 release from earlier today

**Comment by miigotu** [comment]
@knockreff type `errorvwr` in cmd and check what the service logs say.

**Comment by knockreff** [comment]
did a clean install
`eventvwr`  instead of `errorvwr`  shows nssm trying to start every few minutes 

![image](https://user-images.githubusercontent.com/19656948/125477152-a69389f5-b572-42f9-8789-71034370060e.png)

basic sequence since evtx files aren't allowed
"Started C:\SickChill\Python3\tools\python.exe "C:\SickChill\Python3\tools\Scripts\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data" for service SickChill in C:\SickChill\Data."

Program C:\SickChill\Python3\tools\python.exe for service SickChill exited with return code 1.

kill process tree, kill process tree

Service SickChill action for exit code 1 is Restart. Attempting to restart C:\SickChill\Python3\tools\python.exe.

Service SickChill ran for less than 1500 milliseconds. Restart will be delayed by 256000 milliseconds.

**Comment by huhwhatwho** [comment]
I am getting a python error installing on an x86 system.  It looks like the new installer is downloading the x64 version and it fails to install.

**Comment by miigotu** [comment]
@huhwhatwho x86 is no longer supported, what device is this for? nuget python does not support x86

**Comment by miigotu** [comment]
@knockreff 
Try and install again, i moved the fork code in 6898f93be7fd1b79f0283298de2470f07478ca77 that should have solved your issue

**Comment by knockreff** [comment]
@miigotu So the update is not solving the issue.  However I have found the issue is with how the service is being set up and trying to run when running from NSSM vs cmd. 

I'm able to start it as a  service if the account for NSSM is specified as the one that installed sickchill.   It seems that allowing nssm to start sickchill as a default local system account or elevating it an generic admin account causes it to be unable to locate some aspects of the environment.  These issues go away if the account is specified

![image](https://user-images.githubusercontent.com/19656948/125685570-d2aabb07-8db9-4131-b9fd-27d91a8b2f83.png)
