### ISSUE TITLE
SickChill will not install on Windows 10

### ISSUE THREAD

**Issue by bruceforsyth** [SickChill/windows-sickchill#33]
Am trying to run the newest v0.6.0 installer on windows and am getting this error:

This is an old version of the SickChill installer. Please get the latest version at ....... Setup will now terminate.

I have downloaded the newest release multiple times and yet to no avail. Is the new installer broken?

**Comment by Caddarn** [comment]
I'm having the exact same issue.

**Comment by bruceforsyth** [comment]
Honestly don't know why it MUST update with the most recent in the installer, as SickChill actually checks ITSELF whether or not there's an update pending.. Perhaps removing this unnecessary feature could help avoid issues like this in the future?

**Comment by Tazzz34** [comment]
I'm having the exact same issue.

**Comment by havoc77** [comment]
+1

**Comment by miigotu** [comment]
Maybe because there is a newer version of the installer, 0.6.1

It checks the installer version because the installer does much more than just download the python from the repo.

**Comment by bruceforsyth** [comment]
https://github.com/SickChill/windows-sickchill/releases

0.6.0 is the most recent

**Comment by Tazzz34** [comment]
The version 0.6.1 of installer is not available

**Comment by miigotu** [comment]
Can I get it pushed?

**Comment by miigotu** [comment]
Done.

**Comment by Tazzz34** [comment]
great, thank you very much

**Comment by miigotu** [comment]
Does it work better? I added back ability to use x86 windows, and ability to run on windows server 2012.

Next, edit the service and set it to run as your user or LocalNetwork

**Comment by bruceforsyth** [comment]
Works great - good stuff, many thanks

**Comment by havoc77** [comment]
Thanks.
