### ISSUE TITLE
Service will not start after sketchy install | Windows Server 2012 R2

### ISSUE THREAD

**Issue by hooligeek** [SickChill/windows-sickchill#35]
I downloaded the latest installer this morning and ran it.

I've attempted install in the current C:\SickChill directory and a new C:\SickChill2 directory.

I m logged in at Administrator which is the only account on the server and have even done a "Run as Administrator".

The installer fails download dependencies initially but eventually completes after clicking Retry multiple times.

![image](https://user-images.githubusercontent.com/59208486/126039765-da033f7f-1a5a-4b67-8649-a822bf574f01.png)

When the installer finally completes the service is stuck in a paused state. 

![image](https://user-images.githubusercontent.com/59208486/126039818-fc82ba74-3974-49de-af2c-1d41c4ae2208.png)

I have run through the process multiple times with the same result.  I apologize if I have missed the fix for this in the closed issues.

What else should I be looking for?

Thanks,

Matt

**Comment by hooligeek** [comment]
![image](https://user-images.githubusercontent.com/59208486/126040330-07b02540-2ed7-4187-8878-cb810ba36e87.png)

**Comment by hooligeek** [comment]
![image](https://user-images.githubusercontent.com/59208486/126040357-874e4cc1-e850-43fd-a023-45ea27bd2890.png)

**Comment by hooligeek** [comment]
I was finally able to capture what I believe to be the problem.

![image](https://user-images.githubusercontent.com/59208486/126359941-8795a4d1-55bd-4347-a3f1-dde9252b9395.png)

**Comment by miigotu** [comment]
x86 or x64 windows? What version of the installer?

**Comment by hooligeek** [comment]
It's x64 and I used the latest installer from commit about 3 days ago.

**Comment by miigotu** [comment]
```cmd
C:\SickChill\Python3\bin\python.exe -m pip install -U pip
```
