### ISSUE TITLE
Update Not Processing

### ISSUE THREAD

**Issue by josurr** [SickChill/windows-sickchill#36]
The service displays that there is an update, but when the update is performed, it brings up an HTTP Error 500 page.

Here is the debug log snippet from when the update was performed:

>AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=6008', version='HTTP/1.1', remote_ip='127.0.0.1')
2021-07-20 09:59:05 ERROR :: MANUAL :: Uncaught exception GET /home/update/?pid=6008 (127.0.0.1)

SickChill info:

Install: pip
Version: v2021.07.14-1
Database Version: 44.5

Python Version: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

SSL Version: OpenSSL 1.1.1k 25 Mar 2021

OS: Windows-10-10.0.19042-SP0

Locale: en_US.cp1252

**Comment by zeeter82** [comment]
I can confirm I have the same issue.

**Comment by mwhitmel** [comment]
Same with a critcal alert '2021-08-20 17:47:58 Uncaught exception %s
%r' Been like this since move to pip.. Not a python guy so struggling to find answers. checked wiki but cant see anything
