### ISSUE TITLE
Latest update location of SickChill.py changes but NSSM isn't updated to reflect this so fails to start.

### ISSUE THREAD

**Issue by augur42** [SickChill/windows-sickchill#38]
Following the just released update the location of SickChill.py has changed again so I had to edit the SickChill Service Argument line in NSSM from 
"C:\SickChill\Python3\tools\Scripts\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
to
"C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"

**Comment by miigotu** [comment]
The original location is back, reinstall or pip install -U sickchill
