### ISSUE TITLE
Some kind of issue connecting to Git and UI is unavailable.

### ISSUE THREAD

**Issue by bpapa9013** [SickChill/windows-sickchill#40]
Just started happening in the last few days. Logs are full of this error and UI is unavailable:
WARNING :: MAIN :: Unable to setup GitHub properly, You are currently being throttled by rate limiting for too many requests - Try adding an access token. Error: 403 {"message": "API rate limit exceeded for [public ip redacted]. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Thus far I have tried:
-restarting the service
-restarting the machine
-uninstalling SickChill (preserve DB), reinstall SickChill
-adding access token/username for Github to config.ini (and restart service)

I noticed in the config.ini the branch was set to "pip", but I couldn't find that branch on the main SickChill github or this one, so a little confused by that.

I'm not real familiar with modern Github (used it a little bit years ago for a large professional project but it's changed a lot since then), hence why I am using this Windows installer version. But I have been using the Windows installer version of SickChill for years with very few problems.

Any help would be appreciated.

**Comment by dvandekraats** [comment]
I have the same problem as well.

**Comment by miigotu** [comment]
Maybe check the regular repo instead of the repo just for the installer? It is fixed, a release was just pushed. There was a bug in the post processor that was fixed a few days ago, but we dont watch this repo for bug reports with sickchill itself.

**Comment by miigotu** [comment]
Also, it says branch "pip" because the installer uses a pip install, not a git install anymore. `python -m pip install -U sickchill` on your cli.

**Comment by bpapa9013** [comment]
As I mentioned I am not particularly familiar with using Github (and have never directly used python) so how would I go about switching repos and updating, I presume there is some documentation somewhere, but I haven't managed to locate it as yet...

**Comment by miigotu** [comment]
The issue tracker is at https://github.com/SickChill/SickChill

**Comment by dvandekraats** [comment]
Hi,

 

Sorry, this is probably not the right way to reach you. Could you close the issue I logged in SickChill/windows-sickchill? I posted my fix for this issue there.

 

Regards,

Derrick.
