### ISSUE TITLE
Windows Installer does not install SickChill

### ISSUE THREAD

**Issue by MrHappy** [SickChill/windows-sickchill#44]
After a recent update my windows install of SickChill failed with
`sqlalchemy.exc.ArgumentError: Type annotation for "Movie.results" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)`

Removing the installation and reinstalling resulted in missing SickChill.

**Comment by miigotu** [comment]
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on [discord](https://discord.gg/FXre9qkHwE). Please raise your issue there instead.
